import { mkdirSync, readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

const SITE_URL = 'https://www.jeselcura.me';
const OG_IMAGE = `${SITE_URL}/assets/og-image.jpg`;
const routes = [
  ['/', 'Fractional Customer Success Manager for SaaS & Shopify | Jesel Cura', 'Fractional customer success manager and operations consultant helping SaaS, Shopify, and service-based teams improve onboarding, support workflows, CRM systems, SOPs, retention, and customer operations.'],
  ['/services','Customer Success Operations Services | Jesel Cura','Services for SaaS, Shopify, and service teams that need clearer onboarding, support workflows, CRM hygiene, SOPs, retention systems, and customer operations.'],
  ['/about','About Jesel Cura | Customer Success Operations Consultant','Learn about Jesel Cura, a fractional customer success manager and operations consultant helping teams improve customer workflows and retention.'],
  ['/experience','Experience | Jesel Cura','Explore Jesel Cura customer success, support operations, onboarding, SOP, CRM, SaaS, and Shopify operations experience.'],
  ['/faq','FAQ | Jesel Cura','Answers to common questions about customer success operations consulting, fractional customer success support, onboarding cleanup, and operations audits.'],
  ['/contact','Contact Jesel Cura | Customer Success Operations Consultant','Contact Jesel Cura to discuss customer success operations, onboarding, support workflows, Shopify operations, retention, SOPs, or an operations audit.'],
  ['/case-studies','Customer Operations Case Studies | Jesel Cura','Case studies showing how customer onboarding, support operations, SOPs, and workflows can be improved for SaaS and Shopify teams.'],
  ['/operations-audit','Operations Audit for Customer Success & Support | Jesel Cura','A focused operations audit for SaaS, Shopify, and service teams that need clearer onboarding, support workflows, CRM systems, SOPs, and retention opportunities.'],
  ['/blog','Customer Success Operations Blog | Jesel Cura','Practical articles on SaaS onboarding, Shopify support workflows, customer operations, SOPs, CRM cleanup, retention, and support operations.'],
  ['/fractional-customer-success-consultant','Fractional Customer Success Consultant | Jesel Cura','Fractional customer success consulting for teams that need better onboarding, customer health visibility, renewal workflows, retention systems, and account operations.'],
  ['/customer-success-operations-consultant','Customer Success Operations Consultant | Jesel Cura','Customer success operations consulting to improve lifecycle workflows, CRM hygiene, reporting, SOPs, handoffs, onboarding, support, and retention systems.'],
  ['/shopify-ecommerce-operations-support','Shopify Ecommerce Operations Support | Jesel Cura','Shopify ecommerce operations support for order workflows, support queues, SOPs, customer communication, returns, product operations, and team coordination.'],
  ['/customer-onboarding-consultant','Customer Onboarding Consultant | Jesel Cura','Customer onboarding consulting for SaaS and service teams that need cleaner kickoff, implementation, handoff, education, and adoption workflows.'],
  ['/customer-onboarding-workflow-cleanup','Customer Onboarding Workflow Cleanup | Jesel Cura','Cleanup support for customer onboarding workflows, handoffs, checklists, templates, CRM steps, and implementation visibility.'],
  ['/support-operations-consultant','Support Operations Consultant | Jesel Cura','Support operations consulting for teams that need better ticket triage, macros, escalation paths, knowledge base processes, QA, and reporting.'],
  ['/support-sops-crm-workflow-improvements','Support SOPs & CRM Workflow Improvements | Jesel Cura','Improve support SOPs, CRM workflows, documentation, customer communication, escalation paths, and recurring operational routines.'],
  ['/sop-consultant','SOP Consultant for Customer Operations | Jesel Cura','SOP consulting for customer success, support, onboarding, Shopify operations, CRM maintenance, and recurring customer workflows.'],
  ['/customer-retention-consultant','Customer Retention Consultant | Jesel Cura','Customer retention consulting to improve lifecycle moments, renewal readiness, health signals, customer communication, and post-onboarding workflows.'],
  ['/shopify-operations-support','Shopify Operations Support | Jesel Cura','Shopify operations support for customer service workflows, order follow-up, returns, product updates, SOPs, and recurring store operations.'],
  ['/blog/improve-saas-customer-onboarding','How to Improve SaaS Customer Onboarding | Jesel Cura','A practical guide to improving SaaS customer onboarding with clearer milestones, handoffs, customer education, CRM visibility, and adoption workflows.'],
  ['/blog/shopify-customer-support-workflow-checklist','Shopify Customer Support Workflow Checklist | Jesel Cura','A Shopify support workflow checklist for customer inquiries, order questions, returns, macros, escalation rules, and recurring support improvements.'],
  ['/case-studies/saas-onboarding-workflow-case-study','SaaS Onboarding Workflow Case Study | Jesel Cura','A case study showing how a SaaS onboarding workflow can be clarified with better handoffs, milestones, SOPs, and customer success visibility.'],
  ['/case-studies/shopify-support-operations-case-study','Shopify Support Operations Case Study | Jesel Cura','A case study showing how Shopify support operations can be improved with clearer queues, SOPs, templates, and escalation workflows.'],
];
function canon(path){ return path === '/' ? `${SITE_URL}/` : `${SITE_URL}${path}/`; }
function inject(html,[path,title,desc]){ return html.replace(/<title>.*?<\/title>/s,`<title>${title}</title>`).replace(/<meta name="description" content="[^"]*" \/>/,`<meta name="description" content="${desc}" />`).replace(/<link rel="canonical" href="[^"]*" \/>/,`<link rel="canonical" href="${canon(path)}" />`).replace(/<meta property="og:url" content="[^"]*" \/>/,`<meta property="og:url" content="${canon(path)}" />`).replace(/<meta property="og:title" content="[^"]*" \/>/,`<meta property="og:title" content="${title}" />`).replace(/<meta property="og:description" content="[^"]*" \/>/,`<meta property="og:description" content="${desc}" />`).replace(/<meta property="og:image" content="[^"]*" \/>/,`<meta property="og:image" content="${OG_IMAGE}" />`).replace(/<meta name="twitter:title" content="[^"]*" \/>/,`<meta name="twitter:title" content="${title}" />`).replace(/<meta name="twitter:description" content="[^"]*" \/>/,`<meta name="twitter:description" content="${desc}" />`).replace(/<meta name="twitter:image" content="[^"]*" \/>/,`<meta name="twitter:image" content="${OG_IMAGE}" />`); }
const template=readFileSync('dist/index.html','utf8');
for(const route of routes){ const target=route[0]==='/'?'dist/index.html':join('dist',route[0],'index.html'); mkdirSync(dirname(target),{recursive:true}); writeFileSync(target,inject(template,route)); }
writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+routes.map(([p])=>`  <url><loc>${canon(p)}</loc><lastmod>2026-06-30</lastmod><changefreq>${p==='/'?'weekly':'monthly'}</changefreq><priority>${p==='/'?'1.0':'0.8'}</priority></url>`).join('\n')+'\n</urlset>\n');
if (existsSync('public/robots.txt')) copyFileSync('public/robots.txt','dist/robots.txt');
